version: '3'


services:
    app:
      build: .
      container_name: conceptu-app
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/home/django/app
      ports:
        - "8000:8000"
      depends_on:
        - db


    db:
      image: postgres
      container_name: conceptu-db
      tty:  true
      environment:
        - POSTGRES_DB=conceptu
        - POSRGRES_USER=postgres
        - POSTGRES_PASSWORD=root
      volumes:
        - nave-pgdata:/var/lib/postgresql/data
    
    

volumes:
  nave-pgdata:
    external: true
 