# Generated by Django 4.0.3 on 2022-03-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_category_owner_category_public_folder_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
